/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchoolsIndexRouteImport } from './routes/schools.index'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as SchoolsCompareRouteImport } from './routes/schools.compare'
import { Route as SchoolsSlugRouteImport } from './routes/schools.$slug'
import { Route as EnquiryThanksRouteImport } from './routes/enquiry.thanks'
import { Route as EnquireSchoolPlacementRouteImport } from './routes/enquire.school-placement'
import { Route as AthletexScholarshipRouteImport } from './routes/athletex.scholarship'
import { Route as ApiEnquiriesRouteImport } from './routes/api/enquiries'

const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsIndexRoute = SchoolsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SchoolsRoute,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgrammesRoute,
} as any)
const SchoolsCompareRoute = SchoolsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => SchoolsRoute,
} as any)
const SchoolsSlugRoute = SchoolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SchoolsRoute,
} as any)
const EnquiryThanksRoute = EnquiryThanksRouteImport.update({
  id: '/enquiry/thanks',
  path: '/enquiry/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireSchoolPlacementRoute = EnquireSchoolPlacementRouteImport.update({
  id: '/school-placement',
  path: '/school-placement',
  getParentRoute: () => EnquireRoute,
} as any)
const AthletexScholarshipRoute = AthletexScholarshipRouteImport.update({
  id: '/athletex/scholarship',
  path: '/athletex/scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnquiriesRoute = ApiEnquiriesRouteImport.update({
  id: '/api/enquiries',
  path: '/api/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/enquire': typeof EnquireRouteWithChildren
  '/process': typeof ProcessRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/athletex/scholarship': typeof AthletexScholarshipRoute
  '/enquire/school-placement': typeof EnquireSchoolPlacementRoute
  '/enquiry/thanks': typeof EnquiryThanksRoute
  '/schools/$slug': typeof SchoolsSlugRoute
  '/schools/compare': typeof SchoolsCompareRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/schools/': typeof SchoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/enquire': typeof EnquireRouteWithChildren
  '/process': typeof ProcessRoute
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/athletex/scholarship': typeof AthletexScholarshipRoute
  '/enquire/school-placement': typeof EnquireSchoolPlacementRoute
  '/enquiry/thanks': typeof EnquiryThanksRoute
  '/schools/$slug': typeof SchoolsSlugRoute
  '/schools/compare': typeof SchoolsCompareRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/schools': typeof SchoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/enquire': typeof EnquireRouteWithChildren
  '/process': typeof ProcessRoute
  '/programmes': typeof ProgrammesRouteWithChildren
  '/schools': typeof SchoolsRouteWithChildren
  '/api/enquiries': typeof ApiEnquiriesRoute
  '/athletex/scholarship': typeof AthletexScholarshipRoute
  '/enquire/school-placement': typeof EnquireSchoolPlacementRoute
  '/enquiry/thanks': typeof EnquiryThanksRoute
  '/schools/$slug': typeof SchoolsSlugRoute
  '/schools/compare': typeof SchoolsCompareRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/schools/': typeof SchoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand'
    | '/enquire'
    | '/process'
    | '/programmes'
    | '/schools'
    | '/api/enquiries'
    | '/athletex/scholarship'
    | '/enquire/school-placement'
    | '/enquiry/thanks'
    | '/schools/$slug'
    | '/schools/compare'
    | '/programmes/'
    | '/schools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand'
    | '/enquire'
    | '/process'
    | '/api/enquiries'
    | '/athletex/scholarship'
    | '/enquire/school-placement'
    | '/enquiry/thanks'
    | '/schools/$slug'
    | '/schools/compare'
    | '/programmes'
    | '/schools'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand'
    | '/enquire'
    | '/process'
    | '/programmes'
    | '/schools'
    | '/api/enquiries'
    | '/athletex/scholarship'
    | '/enquire/school-placement'
    | '/enquiry/thanks'
    | '/schools/$slug'
    | '/schools/compare'
    | '/programmes/'
    | '/schools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandRoute: typeof BrandRoute
  EnquireRoute: typeof EnquireRouteWithChildren
  ProcessRoute: typeof ProcessRoute
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  SchoolsRoute: typeof SchoolsRouteWithChildren
  ApiEnquiriesRoute: typeof ApiEnquiriesRoute
  AthletexScholarshipRoute: typeof AthletexScholarshipRoute
  EnquiryThanksRoute: typeof EnquiryThanksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/': {
      id: '/schools/'
      path: '/'
      fullPath: '/schools/'
      preLoaderRoute: typeof SchoolsIndexRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/schools/compare': {
      id: '/schools/compare'
      path: '/compare'
      fullPath: '/schools/compare'
      preLoaderRoute: typeof SchoolsCompareRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/schools/$slug': {
      id: '/schools/$slug'
      path: '/$slug'
      fullPath: '/schools/$slug'
      preLoaderRoute: typeof SchoolsSlugRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/enquiry/thanks': {
      id: '/enquiry/thanks'
      path: '/enquiry/thanks'
      fullPath: '/enquiry/thanks'
      preLoaderRoute: typeof EnquiryThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire/school-placement': {
      id: '/enquire/school-placement'
      path: '/school-placement'
      fullPath: '/enquire/school-placement'
      preLoaderRoute: typeof EnquireSchoolPlacementRouteImport
      parentRoute: typeof EnquireRoute
    }
    '/athletex/scholarship': {
      id: '/athletex/scholarship'
      path: '/athletex/scholarship'
      fullPath: '/athletex/scholarship'
      preLoaderRoute: typeof AthletexScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiries': {
      id: '/api/enquiries'
      path: '/api/enquiries'
      fullPath: '/api/enquiries'
      preLoaderRoute: typeof ApiEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EnquireRouteChildren {
  EnquireSchoolPlacementRoute: typeof EnquireSchoolPlacementRoute
}

const EnquireRouteChildren: EnquireRouteChildren = {
  EnquireSchoolPlacementRoute: EnquireSchoolPlacementRoute,
}

const EnquireRouteWithChildren =
  EnquireRoute._addFileChildren(EnquireRouteChildren)

interface ProgrammesRouteChildren {
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

interface SchoolsRouteChildren {
  SchoolsSlugRoute: typeof SchoolsSlugRoute
  SchoolsCompareRoute: typeof SchoolsCompareRoute
  SchoolsIndexRoute: typeof SchoolsIndexRoute
}

const SchoolsRouteChildren: SchoolsRouteChildren = {
  SchoolsSlugRoute: SchoolsSlugRoute,
  SchoolsCompareRoute: SchoolsCompareRoute,
  SchoolsIndexRoute: SchoolsIndexRoute,
}

const SchoolsRouteWithChildren =
  SchoolsRoute._addFileChildren(SchoolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandRoute: BrandRoute,
  EnquireRoute: EnquireRouteWithChildren,
  ProcessRoute: ProcessRoute,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  SchoolsRoute: SchoolsRouteWithChildren,
  ApiEnquiriesRoute: ApiEnquiriesRoute,
  AthletexScholarshipRoute: AthletexScholarshipRoute,
  EnquiryThanksRoute: EnquiryThanksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
